name       : xorg-driver-video-rage128
version    : 6.10.2
release    : 4
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-r128-6.10.2.tar.bz2 : 84da21517f3af7617fdf341e84ccb22444d6cdab1647e4808fa631528b9a77de
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : ATi Rage 128 Video Driver
description: |
    The Xorg R128 Driver package contains the X.Org Video Driver for ATI Rage 128 based video cards.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure --enable-kms-only \
               --with-default-accel=sna
build      : |
    %make
install    : |
    %make_install
