name       : xorg-driver-video-rage128
version    : 6.11.0
release    : 7
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-r128-6.11.0.tar.gz : fcd91f498a7623d24713de912d82c58f15a5a3bba0a7a4a6a1638b6d379b3f14
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : ATi Rage 128 Video Driver
description: |
    The Xorg R128 Driver package contains the X.Org Video Driver for ATI Rage 128 based video cards.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure --enable-kms-only \
               --with-default-accel=sna
build      : |
    %make
install    : |
    %make_install
