name       : xorg-driver-video-rage128
version    : 6.12.0
release    : 13
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-r128-6.12.0.tar.gz : b725eb05848fa504f8156452cef4d279969ceac16921113b2663cdcafdcc157c
license    : MIT
component  : xorg.driver
summary    : ATi Rage 128 Video Driver
description: |
    The Xorg R128 Driver package contains the X.Org Video Driver for ATI Rage 128 based video cards.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %configure --enable-kms-only \
               --with-default-accel=sna
build      : |
    %make
install    : |
    %make_install
